export const MOCK_COFFEE = [
  {
    id: 1,
    name: 'Midnight Espresso',
    name_am: 'የእኩለ ሌሊት ኤስፕሬሶ',
    name_om: 'Espiresoo Halkan Gidduu',
    price: 450,
    rating: 4.9,
    category: 'Specialty',
    origin: 'Jimma',
    roast: 'Dark Roast',
    imageUrl: 'https://images.unsplash.com/photo-1510972527921-ce03766a1cf1?w=800&auto=format&fit=crop',
    description: 'A bold, dark-roasted blend with intense notes of dark chocolate and toasted nuts.'
  },
  {
    id: 2,
    name: 'Sidamo Sun-Dried',
    name_am: 'በፀሐይ የደረቀ ሲዳሞ',
    name_om: 'Sidaamoo Aduun Goge',
    price: 380,
    rating: 4.7,
    category: 'Single Origin',
    origin: 'Sidama',
    roast: 'Medium Roast',
    imageUrl: 'https://images.unsplash.com/photo-1521017432531-fbd92d744264?w=800&auto=format&fit=crop',
    description: 'Vibrant and fruity with a heavy berry profile and a smooth, syrupy body.'
  },
  {
    id: 3,
    name: 'Yirgacheffe Floral',
    name_am: 'ይርጋጨፌ አበባማ',
    name_om: 'Yirgaaceffee Urgaawaa',
    price: 420,
    rating: 4.8,
    category: 'Single Origin',
    origin: 'Yirgacheffe',
    roast: 'Light Roast',
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&auto=format&fit=crop',
    description: 'Famous for its jasmine-like floral aroma and bright, lemony acidity.'
  },
  {
    id: 4,
    name: 'Harar Golden Bean',
    name_am: 'የሐረር ወርቃማ ፍሬ',
    name_om: 'Harar Bunni Warqee',
    price: 410,
    rating: 4.6,
    category: 'Organic',
    origin: 'Harar',
    roast: 'Medium Roast',
    imageUrl: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=800&auto=format&fit=crop',
    description: 'Exotic flavor with notes of wild berries and a wine-like acidity.'
  },
  {
    id: 5,
    name: 'Guji Highland Special',
    name_am: 'የጉጂ ከፍተኛ ቦታ ልዩ',
    name_om: 'Guji Highland Special',
    price: 460,
    rating: 5.0,
    category: 'Specialty',
    origin: 'Guji',
    roast: 'Light Roast',
    imageUrl: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&auto=format&fit=crop',
    description: 'Complex and sweet with hints of peach and black tea.'
  },
  {
    id: 6,
    name: 'Buna Ceremony Blend',
    name_am: 'የቡና ስነ-ስርዓት ውህድ',
    name_om: 'Bunni Sirna Aadaa',
    price: 320,
    rating: 4.5,
    category: 'Traditional',
    origin: 'Multi-region',
    roast: 'Dark Roast',
    imageUrl: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=800&auto=format&fit=crop',
    description: 'A traditional roast perfect for the classic Ethiopian coffee ceremony.'
  },
  {
    id: 7,
    name: 'Kaffa Forest Wild',
    name_am: 'የካፋ ዱር ቡና',
    name_om: 'Kaffa Bosona',
    price: 390,
    rating: 4.7,
    category: 'Organic',
    origin: 'Kaffa',
    roast: 'Medium Roast',
    imageUrl: 'https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=800&auto=format&fit=crop',
    description: 'Harvested from wild coffee trees in the birthplace of Arabica.'
  },
  {
    id: 8,
    name: 'Ethiopian Tasting Box',
    name_am: 'የኢትዮጵያ ቡና መቅመሻ ሳጥን',
    name_om: 'Ethiopian Tasting Box',
    price: 850,
    rating: 4.9,
    category: 'Gift Box',
    origin: 'All Regions',
    roast: 'Various',
    imageUrl: 'https://images.unsplash.com/photo-1580915411954-282cb1b0d780?w=800&auto=format&fit=crop',
    description: 'A curated selection of our top 4 regional coffees in 250g bags.'
  },
  {
    id: 9,
    name: 'Limu Estate',
    name_am: 'የሊሙ እርሻ ቡና',
    name_om: 'Limu Estate',
    price: 360,
    rating: 4.6,
    category: 'Single Origin',
    origin: 'Limu',
    roast: 'Medium Roast',
    imageUrl: 'https://images.unsplash.com/photo-1498804103079-a6351b050096?w=800&auto=format&fit=crop',
    description: 'Well-balanced with a spice-like finish and sweet undertones.'
  },
  {
    id: 10,
    name: 'Nekemte Fruity',
    name_am: 'የነቀምት ፍራፍሬያማ',
    name_om: 'Naqamte Fruity',
    price: 340,
    rating: 4.4,
    category: 'Blend',
    origin: 'Wollega',
    roast: 'Light Roast',
    imageUrl: 'https://images.unsplash.com/photo-1506372023823-741c83b836fe?w=800&auto=format&fit=crop',
    description: 'Known for its high body and pleasant fruity acidity.'
  },
  {
    id: 11,
    name: 'Ancient Heirloom',
    name_am: 'ጥንታዊ የቡና ዝርያ',
    name_om: 'Heirloom Durii',
    price: 480,
    rating: 5.0,
    category: 'Specialty',
    origin: 'Illubabor',
    roast: 'Medium Roast',
    imageUrl: 'https://images.unsplash.com/photo-1552344061-11506ec33031?w=800&auto=format&fit=crop',
    description: 'A rare selection of ancient heirloom varieties with a complex profile.'
  },
  {
    id: 12,
    name: 'Cloud Forest Roast',
    name_am: 'የደመናማ ጫካ ቡና',
    name_om: 'Buna Bosona Duumessaa',
    price: 400,
    rating: 4.8,
    category: 'Specialty',
    origin: 'Bonga',
    roast: 'Medium-Dark',
    imageUrl: 'https://images.unsplash.com/photo-1497933321160-f51b7e47af27?w=800&auto=format&fit=crop',
    description: 'Rich and earthy with notes of caramel and forest berries.'
  }
];

export const PAYMENT_DETAILS = {
  telebirr: "0912345678",
  cbeAccount: "1000123456789"
};
